De:
  SWebhosting:
    DatabaseLog:

      # Hint: These settings are used in Objects.yaml and are passed to the LoggerFactory.
      log:
        AccountActionLogger:
          backend: De\SWebhosting\DatabaseLog\Log\DatabaseBackend
          backendOptions:
             severityThreshold: '%LOG_INFO%'
             logIpAddress: TRUE

Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          # Settings for Flow's default loggers
          accountActionLogger:
            default:
              class: De\SWebhosting\DatabaseLog\Log\DatabaseBackend
              options:
                severityThreshold: '%LOG_INFO%'
                logIpAddress: TRUE
